FROM node:9

RUN apt-get update && apt-get install apt-transport-https
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

RUN npm install --global gatsby-cli

COPY build.sh /build.sh

WORKDIR /usr/src/app

ENTRYPOINT /build.sh